module.exports = global.Matter = {
  // style: require('./components/style'),

  utils: {
    CustomDrag: require('./utils/CustomDrag'),
    getStyles: require('./utils/getStyles'),
    MatterBasics: require('./utils/MatterBasics'),
  },
  Styles: require('./styles/Styles'),

  // Accordion: require('./components/accordion/Accordion'),
  // AccordionTab: require('./components/accordion/AccordionTab'),
  Button: require('./components/Button'),
  Checkbox: require('./components/Checkbox'),
  // ColorInput: require('./components/ColorInput'),
  Dropdown: require('./components/Dropdown'),
  // DropdownMenu: require('./components/DropdownMenu'),
  Icon: require('./components/Icon'),
  Input: require('./components/Input'),
  ItemGroup: require('./components/ItemGroup'),
  Label: require('./components/Label'),
  List: require('./components/List'),
  ListItem: require('./components/ListItem'),
  MultiTypeInput: require('./components/MultiTypeInput'),
  Panel: require('./components/Panel'),
  // Slider: require('./components/Slider'),
  Tabs: require('./components/tabs/Tabs'),
  Toggle: require('./components/Toggle'),
  Toolbar: require('./components/Toolbar'),
  ToolbarGroup: require('./components/ToolbarGroup'),
  // Tooltip: require('./components/Tooltip'),
};
